### ISSUE TITLE
Library-level support for glTF in Fantome.Libraries.League

### ISSUE THREAD

**Issue by Crauzer** [Jochem-W/lol2glTF#1]
I recently added support for converting various file formats to glTF using the Fantome library.

You might wanna look into implementing that in your converter as it's probably more stable.

It also supports converting a Simple Skin + Skeleton into a rigged model.

**Comment by Jochem-W** [comment]
Closing this since I've decided to stop working on my lol2glTF because yours just works much better. Since you're also going to add a GUI at some time in the future, I don't really see a need for mine. This might also clear up some confusion because right now there are two programs named lol2gltf.
